### ISSUE TITLE
[FE] 개발환경 구축

### ISSUE THREAD

**Issue by sungik-choi** [codesquad-member-2020/airbnb-09#6]
### Done

- [x] react
- [x] typescript
- [x] webpack
- [x] babel
- [x] alias(절대경로) 적용
- [x] webpack --- production mode 추가
- [x] eslint, prettier 적용

### Todo

- [x] React Router

**Comment by sungik-choi** [comment]
- [React + TypeScript + Webpack](https://medium.com/chequer/theme-in-react-js-dbf5377d0890)
- [ESLint TypeScript에 적용하기](https://ivvve.github.io/2019/10/09/js/ts/typescript-eslint&airbnb/)
- [React Styled-components 적용하기](https://dev-yakuza.github.io/ko/react/styled-components/)

**Comment by reesekimm** [comment]
- [create-react-app 에서 absolute path 와 alias path 사용하기](https://lofty87.github.io/nodejs/react/20190805/create-react-app-absolute-path)
- [My airbnb based ESLint config for "typescript-eslint" with React & prettier](https://gist.github.com/1natsu172/a65a4b45faed2bd3fa74b24163e4256e)
